org: steinko

app: continuose-delivery-template
service: webservice

provider:
  name: aws
  runtime: nodejs14.x
plugins:
  - serverless-finch
custom:
  client:
    bucketName: frontend
    distributionFolder: build
