image: openjdk:15

stages:
  - build
  - test
  - package
  - deploy


build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - ./app/build/libs/app.jar 


test:
  stage: test
  script:
    - ./gradlew check

package:
   image: docker:latest
   services:
     - docker:dind
   stage: package
   script:
     - docker build -t steinko/gradle-ci-cd .
     - docker login -u steinko -p RoxyMusic11
     - docker push steinko/gradle-ci-cd
