default:
  image: openjdk:15
 
stages:
  - continuose-intgeration
  - infrastructure-provision
  - deployment_test
  - acceptance-test
  - infrastructure-destruction

 
backend-integration-test:
  stage: continuose-intgeration
  script:
    - ./gradlew chec

backend-generate-code-coverage:
  stage: continuose-intgeration
  script:
    - ./gradlew jacocoTestReport

backend-generate-java-doc:
  stage: continuose-intgeration
  script:
    - ./gradlew javadoc

backend-check-code-quality:
  stage: continuose-intgeration
  script:
    - ./gradlew sonarqube

frontend-integration-test:
  stage: continuose-intgeration
  image: node
  before_script:
    - cd frontend
  script:
    - npm install
    - npm run test -- --coverage --watchAll=false
    - cd ..

frontend-lint:
  stage: continuose-intgeration
  image: node
  before_script:
    - cd frontend
  script:
    - npm install
    - npm run lint
    - cd ..

backend-assemble-artefact:
  stage: continuose-intgeration
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - ./app/build/libs/app.jar 

provide-infrastructure:
   image: pulumi/pulumi-nodejs
   
   stage: infrastructure-provision
   script:
    - cd deploymentaws
    - npm install
    - export PULUMI_ACCESS_TOKEN="$PULUMI_ACCESS_TOKEN"
    - pulumi login
    - pulumi stack select dev
    - pulumi up -y
    - cd ..
   environment:
    name: test

deployment_test:
    image: node
    stage: deployment_test
    script:
      - cd infAsCodeIntTest
      - npm install
      - npm test
      - cd ..

destroy-infrastructure:
   image: pulumi/pulumi-nodejs
   stage: infrastructure-destruction
   script:
    - cd deploymentaws
    - npm install
    - export PULUMI_ACCESS_TOKEN="$PULUMI_ACCESS_TOKEN"
    - pulumi login
    - pulumi stack select dev
    - pulumi destroy -y
    - cd ..

provide-infrastructure:
   image: pulumi/pulumi-nodejs
   
   stage: infrastructure-provision
   script:
    - cd deploymentaws
    - npm install
    - export PULUMI_ACCESS_TOKEN="$PULUMI_ACCESS_TOKEN"
    - pulumi login
    - pulumi stack select dev
    - pulumi up -y
    - cd ..
   environment:
    name: production

deployment_test:
    image: node
    stage: deployment_test
    script:
      - cd infAsCodeIntTest
      - npm install
      - npm test
      - cd ..

destroy-infrastructure:
   image: pulumi/pulumi-nodejs
   stage: infrastructure-destruction
   script:
    - cd deploymentaws
    - npm install
    - export PULUMI_ACCESS_TOKEN="$PULUMI_ACCESS_TOKEN"
    - pulumi login
    - pulumi stack select dev
    - pulumi destroy -y
    - cd ..