default:
  image: openjdk:15

  
stages:
  - integration-test
  - build-image
  - provide-infrastructure
  - deployment-test
  - acceptance-test
  - destroy-infrastructure

integration-test:
  stage: integration-test
  script:
    - ./gradlew check

infrastructure-unit-test:
  stage: integration-test
  image: ubuntu
  script:
    - chmod +x ./infAsCode/scripts/*.sh
    - ./infAsCode/scripts/npm-install.sh
    - cd  infAsCode
    - npm install
    - cd ..


generate-code-coverage:
  stage: integration-test
  script:
    - ./gradlew jacocoTestReport

generate-java-doc:
  stage: integration-test
  script:
    - ./gradlew javadoc

check-code-quality:
  stage: integration-test
  script:
    - ./gradlew sonarqube

integration-test-frontend:
  stage: integration-test
  image: ubuntu
  before_script:
    - cd frontend
    - chmod +x ./scripts/*.sh
    - ./scripts/npm-install.sh
  script:
    - npm run test -- --coverage --watchAll=false
    - cd ..

lint-frontend:
  stage: integration-test
  image: ubuntu
  before_script:
    - cd frontend
    - chmod +x ./scripts/*.sh
    - ./scripts/npm-install.sh
  script:
    - npm run lint
    - cd ..

assemble-artefact:
  stage: integration-test
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - ./app/build/libs/app.jar 


build-backend-image:
   image: ubuntu
   stage: build-image
   script:
     - apt update -y
     - apt upgrade -y
     - apt install apt-transport-https  ca-certificates curl gnupg lsb-release -y
     - apt install curl -y
     - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
     - echo  "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" |  tee /etc/apt/sources.list.d/docker.list > /dev/null
     - apt update -y
     - export tzdata=Europe/OSLO
     - export DEBIAN_FRONTEND=noninteractive
     - ln -snf /usr/share/zoneinfo/$tzdata /etc/localtime && echo $tzdata > /etc/timezone
     - apt update -y
     - apt install docker-ce docker-ce-cli containerd.io -y tzdata
     - apt update -y
     - service docker start
     - service docker restart
     - service docker status
     - docker run hello-world
     - export DOCKER_CLI_EXPERIMENTAL=enabled
     - docker buildx install
     - docker run --privileged --rm tonistiigi/binfmt --install all 
     - docker context create node-amd64  --from default
     - docker context create node-arm64  --from default
     - docker buildx create --use --name mybuild node-amd64 
     - docker buildx create --append --name mybuild node-arm64
     - docker login -u steinko -p $DOCKER_PASSWORD
     - docker buildx build --platform linux/amd64 --push -t steinko/helloworld-backend .
   
build-frontend-image:
   image: ubuntu
   stage: build-image
   script:
     - apt update -y
     - apt upgrade -y
     - apt install apt-transport-https  ca-certificates curl gnupg lsb-release -y
     - apt install curl -y
     - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
     - echo  "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" |  tee /etc/apt/sources.list.d/docker.list > /dev/null
     - apt update -y
     - export tzdata=Europe/OSLO
     - export DEBIAN_FRONTEND=noninteractive
     - ln -snf /usr/share/zoneinfo/$tzdata /etc/localtime && echo $tzdata > /etc/timezone
     - apt update -y
     - apt install docker-ce docker-ce-cli containerd.io -y tzdata
     - apt update -y
     - service docker start
     - service docker restart
     - service docker status
     - cd frontend
     - docker run hello-world
     - export DOCKER_CLI_EXPERIMENTAL=enabled
     - docker buildx install
     - docker run --privileged --rm tonistiigi/binfmt --install all 
     - docker context create node-amd64  --from default
     - docker context create node-arm64  --from default
     - docker buildx create --use --name mybuild node-amd64 
     - docker buildx create --append --name mybuild node-arm64
     - docker login -u steinko -p $DOCKER_PASSWORD
     - docker buildx build --platform linux/amd64 --push -t steinko/helloworld-frontend .
   


provide-infrastructure:
   image: ubuntu
   stage: provide-infrastructure
   before_script:
    - chmod +x ./infAsCode/scripts/*.sh
    - ./infAsCode/scripts/setup.sh
   script:
    - ./infAsCode/scripts/run-pulumi.sh

deployment-test:
  stage: deployment-test
  image: golang:latest
  before_script:
    - cd infIntTest
    - export PATH=$PATH:$(dirname $(go list -f '{{.Target}}' .))
    - go get github.com/cucumber/godog/cmd/godog@v0.11.0
    - export PATH=$PATH:$(dirname $(go list -f '{{.Target}}' .))
  script:
    - godog
    - cd ..

   

acceptance-test:
  image: gradle
  stage: acceptance-test
  
  script:
    - cd ./acceptanceTest
    - gradle cucumber
    - cd ..

destroy-infrastructure:
   image: ubuntu
   stage: destroy-infrastructure
   before_script:
    - chmod +x ./infAsCode/scripts/*.sh
    - ./infAsCode/scripts/setup.sh

   script:
    - ./infAsCode/scripts/destroy-pulumi.sh
  
 
