default:
  image: openjdk:15
 
stages:
  - continuose-intgeration
  - test-infrastructure-provision
  - test-deployment-test
  - acceptance-test
  - test-infrastructure-destruction
  - production-infrastructure-provision
  - production-deployment-test
  - production-infrastructure-destruction

 
backend-integration-test:
  stage: continuose-intgeration
  script:
    - ./gradlew check

backend-generate-code-coverage:
  stage: continuose-intgeration
  script:
    - ./gradlew jacocoTestReport

backend-generate-java-doc:
  stage: continuose-intgeration
  script:
    - ./gradlew javadoc

backend-check-code-quality:
  stage: continuose-intgeration
  script:
    - ./gradlew sonarqube

frontend-integration-test:
  stage: continuose-intgeration
  image: node
  before_script:
    - cd frontend
  script:
    - npm install
    - npm run test -- --coverage --watchAll=false
    - cd ..

frontend-lint:
  stage: continuose-intgeration
  image: node
  before_script:
    - cd frontend
  script:
    - npm install
    - npm run lint
    - cd ..

backend-assemble-artefact:
  stage: continuose-intgeration
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - ./app/build/libs/app.jar 

provide-infrastructure-test:
   image: pulumi/pulumi-nodejs
   
   stage: test-infrastructure-provision
   script:
    - cd deploymentaws
    - npm install
    - export PULUMI_ACCESS_TOKEN="$PULUMI_ACCESS_TOKEN"
    - pulumi login
    - pulumi stack select dev
    - pulumi up -y
    - cd ..
   environment:
    name: test

test-deployment-test:
    image: node
    stage: test-deployment-test
    script:
      - cd infAsCodeIntTest
      - npm install
      - npm test
      - cd ..

destroy-test-infrastructure:
   image: pulumi/pulumi-nodejs
   stage: test-infrastructure-destruction
   script:
    - cd deploymentaws
    - npm install
    - export PULUMI_ACCESS_TOKEN="$PULUMI_ACCESS_TOKEN"
    - pulumi login
    - pulumi stack select test
    - pulumi destroy -y
    - cd ..

provide-infrastructure-production:
   image: pulumi/pulumi-nodejs
   stage: production-infrastructure-provision
   script:
    - cd deploymentaws
    - npm install
    - export PULUMI_ACCESS_TOKEN="$PULUMI_ACCESS_TOKEN"
    - pulumi login
    - pulumi stack select production
    - pulumi up -y
    - cd ..
   environment:
    name: production

production-deployment-test:
    image: node
    stage: deployment-test-production
    script:
      - cd infAsCodeIntTest
      - npm install
      - npm test
      - cd ..

destroy-infrastructure-production:
   image: pulumi/pulumi-nodejs
   stage: production-infrastructure-destruction
   script:
    - cd deploymentaws
    - npm install
    - export PULUMI_ACCESS_TOKEN="$PULUMI_ACCESS_TOKEN"
    - pulumi login
    - pulumi stack select production
    - pulumi destroy -y
    - cd ..