default:
  image: openjdk:15

  
stages:
  - build
  - test
  - package
  - infrastructure-update
  - systemtest
  - deploy


build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - ./app/build/libs/app.jar 


test:
  stage: test
  script:
    - ./gradlew check

package:
   image: ubuntu
   stage: package
   script:
     - apt update -y
     - apt upgrade -y
     - apt install apt-transport-https  ca-certificates curl gnupg lsb-release -y
     - apt install curl -y
     - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
     - echo  "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" |  tee /etc/apt/sources.list.d/docker.list > /dev/null
     - apt update -y
     - export tzdata=Europe/OSLO
     - export DEBIAN_FRONTEND=noninteractive
     - ln -snf /usr/share/zoneinfo/$tzdata /etc/localtime && echo $tzdata > /etc/timezone
     - apt update -y
     - apt install docker-ce docker-ce-cli containerd.io -y tzdata
     - service docker start
     - service docker status
     - docker run hello-world
     - export DOCKER_CLI_EXPERIMENTAL=enabled
     - docker buildx install
     - docker run --privileged --rm tonistiigi/binfmt --install all 
     - docker context create node-amd64  --from default
     - docker context create node-arm64  --from default
     - docker buildx create --use --name mybuild node-amd64 
     - docker buildx create --append --name mybuild node-arm64
     - docker login -u steinko -p RoxyMusic11
     - docker buildx build --platform linux/amd64 --push -t steinko/gradle-ci-cd .

pulumi:
   image: ubuntu
   stage: infrastructure-update
   before_script:
    - chmod +x ./infAsCode/scripts/*.sh
    - ./infAsCode/scripts/setup.sh
   script:
    - ./infAsCode/scripts/run-pulumi.sh
   only:
     - master
 
  
pulumi-preview:
  image: ubuntu
  stage: infrastructure-update
  before_script:
    - chmod +x ./infAsCode/scripts/*.sh
    - ./infAsCode/scripts/setup.sh
  script:
    - ./infAsCode/scripts/pulumi-preview.sh
  only:
  - merge_requests

systemtest:
  image: ubuntu
  stage: systemtest
  script:
    - apt install openjdk-15-jdk
    - export JAVA_HOME=/usr/lib/jvm/openjdk-15-jdk
    - export PATH=$PATH:$JAVA_HOME/bin
    - ./acceptanceTest/gradlew cucumber
