default:
  image: openjdk:15
 
stages:
  - continuose-intgeration
  - infrastructure-provision
  - deployment_test
  - acceptance-test
  - infrastructure-destruction

 
backend-integration-test:
  stage: continuose-intgeration
  script:
    - ./gradlew chec

backend-generate-code-coverage:
  stage: continuose-intgeration
  script:
    - ./gradlew jacocoTestReport

backend-generate-java-doc:
  stage: continuose-intgeration
  script:
    - ./gradlew javadoc

backend-check-code-quality:
  stage: continuose-intgeration
  script:
    - ./gradlew sonarqube

frontend-integration-test:
  stage: continuose-intgeration
  image: node
  before_script:
    - cd frontend
  script:
    - npm install
    - npm run test -- --coverage --watchAll=false
    - cd ..

frontend-lint:
  stage: continuose-intgeration
  image: node
  before_script:
    - cd frontend
  script:
    - npm install
    - npm run lint
    - cd ..

backend-assemble-artefact:
  stage: continuose-intgeration
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - ./app/build/libs/app.jar 


deployment_test:
    image: go
    stage: deployment_test
    script:
      - cd infAsCodeRunTimeTest
      - go test
      - cd ..



