image: openjdk:15

stages:
  - build
  - test
  - package
  - infrastructure-update
  - deploy


build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - ./app/build/libs/app.jar 


test:
  stage: test
  script:
    - ./gradlew check

package:
   image: docker:latest
   services:
     - docker:dind
   stage: package
   script:
     - docker build -t steinko/gradle-ci-cd .
     - docker login -u steinko -p RoxyMusic11
     - docker push steinko/gradle-ci-cd

pulumi:
   stage: infrastructure-update
   before_script:
    - chmod +x ./infAsCode/script/*.sh
    - apk update
    - apk add bash
    - apk add curl
    - ./infAsCode/script/setup.sh
   script:
    - ./infAsCode/script/run-pulumi.sh
  # Create an artifact archive with just the pulumi log file,
  # which is created using console-redirection in run-pulumi.sh.
   artifacts:
     paths:
     - pulumi-log.txt
     # This is just a sample of how artifacts can be expired (removed) automatically in GitLab.
     # You may choose to not set this at all based on your organization's or team's preference.
     expire_in: 1 week
   # This job should only be created if the pipeline is created for the master branch.
   only:
   - master

pulumi-preview:
  stage: infrastructure-update
  before_script:
    - chmod +x ./infAsCode/scripts/*.sh
    - ./infAsCode/script/setup.sh
  script:
    - ./infAsCode/scripts/pulumi-preview.sh
  only:
  - merge_requests
