default:
  image: openjdk:15
 
stages:
  - integration-test
  - provide-infrastructure
  - deployment-test
  - acceptance-test
  - destroy-infrastructure

 
backend-integration-test:
  stage: integration-test
  script:
    - ./gradlew chec

backend-generate-code-coverage:
  stage: integration-test
  script:
    - ./gradlew jacocoTestReport

backend-generate-java-doc:
  stage: integration-test
  script:
    - ./gradlew javadoc

backend-check-code-quality:
  stage: integration-test
  script:
    - ./gradlew sonarqube

frontend-integration-test:
  stage: integration-test
  image: node
  before_script:
    - cd frontend
  script:
    - npm install
    - npm run test -- --coverage --watchAll=false
    - cd ..

frontend-lint:
  stage: integration-test
  image: node
  before_script:
    - cd frontend
  script:
    - npm install
    - npm run lint
    - cd ..

backend-assemble-artefact:
  stage: integration-test
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - ./app/build/libs/app.jar 


   
provide-infrastructure:
   image: pulumi/pulumi-nodejs
   
   stage: provide-infrastructure
   script:
    - cd deploymentaws
    - npm install
    - pulumi up
    - cd ..


acceptance-test:
  image: gradle
  stage: acceptance-test
  
  script:
    - cd ./acceptanceTest
    - gradle cucumber
    - cd ..

  
destroy-infrastructure:
   image: pulumi/pulumi-nodejs
   stage: destroy-infrastructure
   script:
    - cd deploymentaws
    - npm install
    - pulumi up
    - cd ..
 
