/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.steinko.helloworld;

import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.SpringApplication;

@SpringBootApplication
public class App {
	
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
    	SpringApplication.run(App.class, args);	
    }
}
